### PR TITLE
React 16 + upgrade of all other dependencies

### PR DESCRIPTION
**Pull request by GarrisonD**

### CODE REVIEW

**Comment by faceyspacey** [comment]
and all is working fine?

**Comment by GarrisonD** [comment]
Sure, in other case I would not create this PR.

**Comment by GarrisonD** [comment]
But it would be really cool, if you could check everything!

**Comment by faceyspacey** [comment]
It's looking very good. Nicely done!

If interested in going further, `renderToNodeStream` is something we may want to implement on the server.

**Pull request merged**
